name: Bazel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Setup BB
        run: |
          echo "build --bes_results_url=https://app.buildbuddy.io/invocation/" >> ~/.bazelrc
          echo "build --bes_backend=grpcs://remote.buildbuddy.io" >> ~/.bazelrc
          echo "common --remote_header=x-buildbuddy-api-key=${{ secrets.BUILD_BUDDY_API_KEY }}" >> ~/.bazelrc
          echo "common --remote_cache=grpcs://remote.buildbuddy.io" >> ~/.bazelrc
          echo "common --remote_timeout=10m" >> ~/.bazelrc


      - name: Test
        run: |
          cd examples
          bazel test //... --test_output=all

      - name: Test json (uncached test results)
        run: |
          cd examples
          bazel test --config=json //... --test_output=all --cache_test_results=no

      - name: Test failing test
        run: |
          cd examples
          ./verify_test_fails.sh
